### ISSUE TITLE
Calling "close()" doesn't fire "d2l-simple-overlay-closed" event

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/simple-overlay#17]
Overlay people, interested in your thoughts here: @CodeBaboon @omsmith @ryantmer @cgalvind2l @trevorjonesd2l 

There's some [code in image-banner-overlay](https://github.com/Brightspace/d2l-image-banner-overlay/blob/master/d2l-image-banner-overlay.html#L290) that depends on the `d2l-simple-overlay-closed` event to toggle a property. That property does CSS things.

The issue I'm seeing though is that when you call `.close()` manually on the overlay, because it calls directly into `iron-overlay-behavior`'s `close()` method, the `d2l-simple-overlay-closed` event never fires. It only fires when you click on the "X" button.

I can fix this easily enough by adding a listener for `iron-overlay-closed` event that fires `d2l-simple-overlay-closed`, but there is the worry that a consumer's event listener is now going to get called when previously it wasn't.

A [code search for "d2l-simple-overlay-closed" event](http://search.dev.d2l/source/search?q=%22d2l-simple-overlay-closed%22&defs=&refs=&path=&hist=&type=&project=GitHub) reveals four such listeners:

- `image-banner-overlay`: this is the case that's actually breaking for me
- [`my-courses`](http://search.dev.d2l/source/xref/GitHub/d2l-my-courses-ui/src/d2l-my-courses-content/d2l-my-courses-content-behavior.html#82): looks like some duplicate code in there that could be cleaned up if the event fired correctly, but also a potential for bug.
- [`image-selector`](http://search.dev.d2l/source/xref/GitHub/image-selector/d2l-basic-image-selector.html#136): it doesn't appear to ever call `.close()`, so should be good
- [`parent-portal`](http://search.dev.d2l/source/xref/GitHub/parent-portal-ui/src/widgets/d2l-upcoming-assessments-widget/d2l-upcoming-assessments-widget.html#118): also doesn't appear to call `.close()`

What do people think? Is there agreement that it should be firing the event? If yes, I'd like to avoid a major version bump... but if we're worried I can.

**Comment by ryantmer** [comment]
Yeah, I think an event makes sense - it's more in line with how `iron-overlay-behavior` works :+1:
